name: Build Windows App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # امکان اجرای دستی بیلد از داخل سایت گیت‌هاب

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-app
          path: build/windows/x64/runner/Release/